#include <stdio.h>
#include "lup_functions.h"

int main(int argc, char **argv) {
    if(argc != 4) {
        fprintf(stderr, "Usage: %s filename_in N filename_out\n", argv[0]);
        fprintf(stderr, "\tN denotes matrix size\n");
        fprintf(stderr, "\tfilename_in - file with initial matrix\n");
        fprintf(stderr, "\tfilename_out - file for results matrix\n");
        return 1;
    }

    char *filename_in = argv[1];
    int N = atoi(argv[2]); // size of matrix
    char *filename_out = argv[3];
    MPI_Init(&argc, &argv);
    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    if(size == 1) {
        fprintf(stderr, "At least 2 processes expected\n");
        MPI_Abort(MPI_COMM_WORLD, 1);
    }
    int i;
    // calculate how many rows goes to every process
    int rows_per_process = N / (size - 1); // (size-1) because rank=0 does not work here
    int rows_per_last_process = N - (size - 2) * rows_per_process;
    int rp = (rank == size - 1) ? rows_per_last_process : rows_per_process; // actual rows_per_process for every process
                                                                            // not significant at rank=0

    double *prev_row = (double*)malloc(sizeof(double) * N); // rank=0 receive this too in MPI_Bcast
                                                            // but it does not use it
    int i_proc; // rank of process, which contains row 'i' (currently processed row)

    double *A = NULL; // initial matrix
    MPI_Win win_A; // window for matrix A (initial matrix)
    if(rank == 0) {
        LUP_mpi_matrix_create(&A, N);
        FILE *f_in;
        f_in = fopen(filename_in, "rb");
        if(!f_in) {
            fprintf(stderr, "Unable to open file '%s'\n", filename_in);
            MPI_Abort(MPI_COMM_WORLD, 1);
        }
        for(i = 0; i < N; i++) { // fill array with data generated by lup_generate_matrix
            fread(A + i*N, sizeof(double), N, f_in); // row by row
        }
        fclose(f_in);
        // end read matrix A from file
        // spread rows across processes
    } // rank=0
    MPI_Win_create(A, N*N*sizeof(double), sizeof(double), MPI_INFO_NULL, MPI_COMM_WORLD, &win_A);
    MPI_Win_fence(0, win_A);
    double *rows = NULL;
    if(rank > 0) {
        rows = (double*)malloc(sizeof(double) * N * rp);
        MPI_Get(rows, N * rp, MPI_DOUBLE, 0, (rank - 1) * rows_per_process * N, N * rp, MPI_DOUBLE, win_A);
    } // rank>0
    MPI_Win_fence(0, win_A);

    if(rank == 0) {
        //double *A = NULL; // initial matrix
        double *C = NULL; // results matrix
        int *P = NULL; // identity matrix
        // read matrix A from file
        LUP_mpi_matrix_create(&C, N);
        P = (int*)malloc(sizeof(int) * N); // matrix P is represented as vector of indexes
                                           // P[i] = k, i - row, k = column, where '1' is located
                                           // to swap rows 'i' and 'j' in P, swap elements P[i] and P[j]
        for(i = 0; i < N; i++) {
            P[i] = i;
        }
        FILE *f_out;
        f_out = fopen(filename_out, "w");
        if(!f_out) {
            fprintf(stderr, "Unable to open file '%s'\n", filename_out);
            return 1;
        }
        /*double *pivot_values = (double*)malloc(sizeof(double) * size);
        int *pivot_rows = (int*)malloc(sizeof(int) * size);
        int proc;
        double proc_max_value;
        int proc_max_row;
        // main loop for rank=0
        for(i = 0; i < N-1; i++) { // last cell of matrix (C[N-1][N-1] does not participate, because it is not necessary
            // get all local pivot_value and pivot_row
            // pivot_values[0] and pivot_rows[0] has been sent from rank=0 and are not significant
            MPI_Gather(pivot_values, 1, MPI_DOUBLE, pivot_values, 1, MPI_DOUBLE, 0, MPI_COMM_WORLD);
            MPI_Gather(pivot_rows, 1, MPI_INT, pivot_rows, 1, MPI_INT, 0, MPI_COMM_WORLD);
            proc_max_value = 0;
            proc_max_row = -1;
            int proc_last_row;
            int max_proc = -1;
            for(proc = 1; proc < size; proc++) {
                if(proc == size - 1) proc_last_row = N-1;
                else proc_last_row = proc*rows_per_process - 1;
                if(i <= proc_last_row) {
                    if(pivot_values[proc] > proc_max_value) {
                        proc_max_value = pivot_values[proc];
                        proc_max_row = pivot_rows[proc];
                        max_proc = proc;
                    }
                }
            }
            //swap rows in P
            //t_swap_rows_in_P += MPI_Wtime() - t_swap_rows_in_P;
            int tmp = P[proc_max_row];
            P[proc_max_row] = P[i];
            P[i] = tmp;
            //t_swap_rows_in_P += MPI_Wtime() - t_swap_rows_in_P;
            MPI_Recv(&i_proc, 1, MPI_INT, MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
            //swap rows in C (swap row i with row proc_max_row, proc_max_row is in process max_proc)
            MPI_Bcast(&i, 1, MPI_INT, 0, MPI_COMM_WORLD);
            MPI_Bcast(&proc_max_row, 1, MPI_INT, 0, MPI_COMM_WORLD);
            MPI_Bcast(&i_proc, 1, MPI_INT, 0, MPI_COMM_WORLD);
            MPI_Bcast(&max_proc, 1, MPI_INT, 0, MPI_COMM_WORLD);
            double dtmp;//not used, just to receive broadcasted C[i][i]
            MPI_Bcast(&dtmp, 1, MPI_DOUBLE, i_proc, MPI_COMM_WORLD);
            MPI_Bcast(prev_row, N, MPI_DOUBLE, i_proc, MPI_COMM_WORLD);//meaningless for root
        } // end main loop for rank=0

        int *recvcounts = (int*)malloc(sizeof(int) * size);
        // already allocated memory for displs
        // displs = (int*)malloc(sizeof(int) * size);
        recvcounts[0] = displs[0] = 0;//rank=0 does not send anything (and does not receive, too)
        for(i = 1; i < size; i++) {
            if(i == size-1) {
                recvcounts[i] = rows_per_last_process * N;
            } else {
                recvcounts[i] = rows_per_process * N;
            }
            displs[i] = (i-1) * recvcounts[i-1];
        }
        MPI_Gatherv(C, 0, MPI_DOUBLE, C, recvcounts, displs, MPI_DOUBLE, 0, MPI_COMM_WORLD);
        free(recvcounts);
        free(displs);
        recvcounts = displs = NULL;
        int k;
        //t_start_data_out = MPI_Wtime();
        fprintf(f_out, "C\n");
        for(i = 0; i < N; i++) {
            for(k = 0; k < N; k++) {
                fprintf(f_out, "%f\t", C[i*N + k]);
            }
            fprintf(f_out, "\n");
        }
        fprintf(f_out, "P\n");
        for(i = 0; i < N; i++) {
            for(k = 0; k < N; k++) {
                if(k == P[i]) {
                    fprintf(f_out, "1\t");
                } else {
                    fprintf(f_out, "0\t");
                }
            }
            fprintf(f_out, "\n");
        }
        fclose(f_out);
        //t_end_data_out = MPI_Wtime();
        LUP_mpi_matrix_free(&A);
        LUP_mpi_matrix_free(&C);
        free(P);
        free(pivot_values);
        free(pivot_rows);
        //fprintf(stderr, "scatter data. time = %f\n", t_scatter_data - t_start);
        //fprintf(stderr, "swap rows in P. time = %f\n", t_swap_rows_in_P - t_start);
        //fprintf(stderr, "DATA OUT. time = %f\n", t_end_data_out - t_start_data_out);
        //fprintf(stderr, "Total time = %f\n", MPI_Wtime() - t_start);
        */
    } // if rank==0

    if(rank > 0) {
        int first_row = -1;
        int last_row = -1;
        // every process finds out, which rows it processes
        // for example
        // if we have 10 rows and 4 processes (including rank=0)
        // then processes with rank 1,2,3 receive rows from rank=0
        // rank=1 receives rows from 0 to 2 (including 2), 3 rows  
        // rank=2 receives rows from 3 to 5 (including 5), 3 rows  3+3+4=10
        // rank =3 reeives rows from 6 to 9 (including 9), 4 rows  
        LUP_find_first_last_rows(rank, size, N, rows_per_process, &first_row, &last_row);

        /*double pivot_value;
        int pivot_row;
        int i_row; // i_row=i (currently processed row)
        int max_row; // max_row - row with maximum element in column 'i'
                     // maximum element is searched for in lines i+1 to N-1 (including N-1) of column 'i'
        int max_proc; // rank of process, which contains max_row
        double Cii;
        // mail loop for rank>0
        for(i = 0; i < N-1; i++) { // last cell of matrix (C[N-1][N-1] does not participate, because it is not necessary
            if(LUP_mpi_find_pivot(rows, first_row, last_row, i, N, &pivot_value, &pivot_row) == 0) { // pivot row found
                if(fabs(pivot_value) < 1E-6) { // too close to 0 (zero)
                    fprintf(stderr, "Matrix is singular\n");
                    MPI_Abort(MPI_COMM_WORLD, 1);
                }
            }
            // send local pivot_row and pivot_value to rank=0
            // so it can find global pivot_value and pivot_row
            MPI_Gather(&pivot_value, 1, MPI_DOUBLE, NULL, 0, MPI_DOUBLE, 0, MPI_COMM_WORLD);
            MPI_Gather(&pivot_row, 1, MPI_INT, NULL, 0, MPI_INT, 0, MPI_COMM_WORLD);
            if(i >= first_row && i <= last_row) {
                MPI_Send(&rank, 1, MPI_INT, 0, 0, MPI_COMM_WORLD);
            }
            MPI_Bcast(&i_row, 1, MPI_INT, 0, MPI_COMM_WORLD);
            MPI_Bcast(&max_row, 1, MPI_INT, 0, MPI_COMM_WORLD);
            MPI_Bcast(&i_proc, 1, MPI_INT, 0, MPI_COMM_WORLD);
            MPI_Bcast(&max_proc, 1, MPI_INT, 0, MPI_COMM_WORLD);
            if(i_row >= first_row && i_row <= last_row && max_row >= first_row && max_row <= last_row) { // both rows are in the same process
                //t_swap_rows_in_the_same_process += MPI_Wtime() - t_swap_rows_in_the_same_process;
                LUP_mpi_swap_rows(rows, i_row, max_row, first_row, N);
                //t_swap_rows_in_the_same_process += MPI_Wtime() - t_swap_rows_in_the_same_process;
            } else if(i_row >= first_row && i_row <= last_row) {
                //t_swap_rows_in_different_processes += MPI_Wtime() - t_swap_rows_in_different_processes;
                MPI_Sendrecv_replace(rows + (i_row - first_row)*N, N, MPI_DOUBLE, max_proc, 0, max_proc, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
                //t_swap_rows_in_different_processes += MPI_Wtime() - t_swap_rows_in_different_processes;
            } else if(max_row >= first_row && max_row <= last_row) {
                //t_swap_rows_in_different_processes += MPI_Wtime() - t_swap_rows_in_different_processes;
                MPI_Sendrecv_replace(rows + (max_row - first_row)*N, N, MPI_DOUBLE, i_proc, 0, i_proc, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
                //t_swap_rows_in_different_processes += MPI_Wtime() - t_swap_rows_in_different_processes;
            }
            //spread C[i][i] across processes
            if(i >= first_row && i <=last_row) {
                MPI_Bcast(rows + (i - first_row)*N + i, 1, MPI_DOUBLE, rank, MPI_COMM_WORLD); 
                Cii = rows[(i-first_row)*N + i];
            } else {
                MPI_Bcast(&Cii, 1, MPI_DOUBLE, i_proc, MPI_COMM_WORLD);
            }
            if(rank == i_proc)
                MPI_Bcast(rows + (i_row - first_row)*N, N, MPI_DOUBLE, i_proc, MPI_COMM_WORLD);
            else
                MPI_Bcast(prev_row, N, MPI_DOUBLE, i_proc, MPI_COMM_WORLD);
            int j, k;
            int start, end;
            //t_calcs += MPI_Wtime() - t_calcs;
            if((i+1) <= last_row) {
                if((i+1) >= first_row)
                    start = i+1;
                else
                    start = first_row;
                end = last_row - first_row;
                start = start - first_row;
                for(j = start; j <= end; j++) {
                    rows[j*N + i] /= Cii;
                    for(k = i+1; k < N; k++) {
                        if(rank == i_proc)
                            rows[j*N + k] -= rows[j*N + i] * rows[(i-first_row) * N + k];
                        else
                            rows[j*N + k] -= rows[j*N + i] * prev_row[k];
                    }
                }
            }
        }
        MPI_Gatherv(rows, N * rp, MPI_DOUBLE, NULL, NULL, NULL, MPI_DOUBLE, 0, MPI_COMM_WORLD);
        */
        free(rows);
        rows = NULL;
    } // if rank>0

    free(prev_row);
    MPI_Win_free(&win_A);

    MPI_Barrier(MPI_COMM_WORLD);
    MPI_Finalize();
    return 0;
}
