#include <stdio.h>
#include "lup_functions.h"

int main(int argc, char **argv) {
    double **A;
    double **C;
    int **P;
    if(argc != 4) {
        fprintf(stderr, "Usage: %s filename_in N filename_out\n", argv[0]);
        fprintf(stderr, "\tN denotes matrix size\n");
        fprintf(stderr, "\tfilename_in - file with initial matrix\n");
        fprintf(stderr, "\tfilename_out - file for results matrix\n");
        return 1;
    }
    char *filename_in = argv[1];
    int N = atoi(argv[2]);
    char *filename_out = argv[3];
    matrix_create((void***)&A, N, sizeof(double));
    matrix_create((void***)&C, N, sizeof(double));
    matrix_create((void***)&P, N, sizeof(int));
    matrix_make_identity_matrix(P, N);

    FILE *f_in, *f_out;
    f_in = fopen(filename_in, "rb");
    if(!f_in) {
        fprintf(stderr, "Unable to open file '%s'\n", filename_in);
        return 1;
    }
    f_out = fopen(filename_out, "w");
    if(!f_out) {
        fprintf(stderr, "Unable to open file '%s'\n", filename_out);
        return 1;
    }
    int i;
    for(i = 0; i < N; i++) {//fill array with data generated by lup_generate_matrix
        fread(A[i], sizeof(double), N, f_in);
    }
    fclose(f_in);
    
    int j, k;
    /*int i, j, k;
    printf("A\n");
    for(i = 0; i < N; i++) {
        for(k = 0; k < N; k++) {
            A[i][k] = i*N + k;
            printf("%.2f\t", A[i][k]);
        }
        printf("\n");
    }*/
    matrix_copy(A, C, N);

    double pivot_value;
    int pivot_row;
    for(i = 0; i < N-1; i++) {
        LUP_find_pivot(C, N, i, &pivot_value, &pivot_row);
        if(pivot_value == 0) {
            fprintf(stderr, "Matrix is singular\n");
            break;
        } else {
            LUP_swap_rows((void**)C, pivot_row, i);
            LUP_swap_rows((void**)P, pivot_row, i);
            for(j = i+1; j < N; j++) {
                C[j][i] /= C[i][i];
                for(k = i+1; k < N; k++) {
                    C[j][k] -= C[j][i] * C[i][k];
                }
            }
        }
        //printf("%d---\n", i);
        //printf("SWAP %d %d\n", pivot_row, i);
        /*int l, l1;
        for(l = 0; l < N; l++) {
            for(l1 = 0; l1 < N; l1++) {
                printf("%f\t", C[l][l1]);
            }
            printf("\n");
        }
        printf("---\n");*/
    }
    fprintf(f_out, "C\n");
    for(i = 0; i < N; i++) {
        for(k = 0; k < N; k++) {
            fprintf(f_out, "%f\t", C[i][k]);
        }
        fprintf(f_out, "\n");
    }
    fprintf(f_out, "P\n");
    for(i = 0; i < N; i++) {
        for(k = 0; k < N; k++) {
            fprintf(f_out, "%d\t", P[i][k]);
        }
        fprintf(f_out, "\n");
    }
    fclose(f_out);

    matrix_free((void***)&P, N);
    matrix_free((void***)&C, N);
    matrix_free((void***)&A, N);
    return 0;
}
